file_format: "1"
id: keyball_nano
name: Keyball_nano
type: shield
url: https://github.com/Yowkees/keyball
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - pointer
  - display
siblings:
  - keyball_nano_left
  - keyball_nano_right
